# Generated by Django 4.2.3 on 2023-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horas_trabajadas', models.PositiveIntegerField()),
                ('fecha_contratacion', models.DateField()),
                ('departamento', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
    ]
